name = "HdivBiotElasticityPaper"
uuid = "10ac652b-182d-4a3d-945b-97c1ecf8dd25"
authors = ["Santiago Badia <santiago.badia@monash.edu>", "Martin Hornkjol <marhorn@math.uio.no>", "Arbaz Khan <arbaz@ma.iitr.ac.in>", "Kent-Andre Mardal <kent-and@simula.no>", "Alberto F. Martin <alberto.f.martin@anu.edu.au>", "Ricardo Ruiz-Baier <ricardo.ruizbaier@monash.edu>"]
version = "1.0.0"

[deps]
BSON = "fbb218c0-5317-5bc6-957e-2ee96dd4b1f0"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DrWatson = "634d3b9d-ee7a-5ddf-bec9-22491ea816e1"
Gridap = "56d4f2e9-7ea1-5844-9cf6-b9c51ca7ce8e"
GridapGmsh = "3025c34a-b394-11e9-2a55-3fee550c04c8"
Krylov = "ba0b0d4f-ebba-5204-a429-3ac8c609bfb7"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Pluto = "c3e4b0f8-55cb-11ea-2926-15256bba5781"
PlutoUI = "7f904dfe-b85e-4ff6-b463-dae2292396a8"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
Gridap = "0.17.17"
GridapGmsh = "0.5.0"
Krylov = "0.9.1"
julia = "1.8"
BSON = "0.3.7"
DataFrames = "1.5.0"
DrWatson = "2.12.5"
LaTeXStrings = "1.3.0"
Plots = "1.38.15"
Pluto = "0.19.26"
PlutoUI = "0.7.51"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
